---

- name: Add repository key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Remove old packages
  become: yes
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Docker without sudo
  block:
    - name: Create a group for "{{ username }}"
      become: yes
      group:
        name: docker
        state: present

    - name: Let a user run docker without sudo
      become: yes
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
        state: present

- name: Start and enable systemd
  systemd:
    enabled: yes
    state: started
    name: docker
